<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoDataUsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('users')->truncate();
        
        DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'uuid' => 'e96caced-b619-4713-a407-98bc8c40b6d1',
                'user_type_id' => 1,
                'full_name' => 'Admin',
                'user_name' => 'admin',
                'profile_image' => NULL,
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'admin@bdtask.com',
                'contact_no' => NULL,
                'email_verified_at' => '2025-04-22 10:56:38',
                'password' => '$2y$10$Zxq27mYqOYYSusf9kqZFTOA35.3hqWO1GLXfdJ2ByXle5V2feT2CS',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-04-22 10:56:38',
                'updated_at' => '2025-04-22 10:56:38',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'uuid' => '6891c787-9626-44d9-ba74-1167d49b3612',
                'user_type_id' => 2,
                'full_name' => 'shaeed',
                'user_name' => 'shaeed',
                'profile_image' => 'users/1748951709376.png',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'ali@gmail.com',
                'contact_no' => '01524362541',
                'email_verified_at' => NULL,
                'password' => '$2y$10$BZurebWQLyKZMRk7ClamEegctAcBQsRdmHAZ.8FQbcqE8URHnefQ.',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-04-24 14:52:41',
                'updated_at' => '2025-06-03 17:55:45',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'uuid' => 'ebe54ab5-ba01-4754-bcb7-997005ddad5b',
                'user_type_id' => 2,
                'full_name' => 'jamil saxona',
                'user_name' => 'jamil saxona',
                'profile_image' => 'users/1751112241972.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'jam@gmail.com',
                'contact_no' => '987868684',
                'email_verified_at' => NULL,
                'password' => '$2y$10$SsgijbFNsMq9r27.6A3Ep.cGctdPvLsRurteHdZ75Z8.jGldni6o2',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-08 03:05:31',
                'updated_at' => '2025-06-29 00:04:01',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'uuid' => 'b3311eff-a0a8-4eb6-b85c-8eff1e57fe45',
                'user_type_id' => 2,
                'full_name' => 'montu mian',
                'user_name' => 'montu mian',
                'profile_image' => 'users/1750842978850.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'jh@gmail.com',
                'contact_no' => '098765678',
                'email_verified_at' => NULL,
                'password' => '$2y$10$UZ1UMk6CXDIHl3bONTsPTOflQl4zMuWaSyLZ5kluWKZtpL72EnFiu',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-25 19:17:40',
                'updated_at' => '2025-06-25 21:16:19',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'uuid' => '70af927c-4247-4e8e-b192-26615e4180ea',
                'user_type_id' => 2,
                'full_name' => 'রতন লাল',
                'user_name' => 'রতন লাল',
                'profile_image' => 'users/1750849139692.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'ratan@gmail.com',
                'contact_no' => '9876545678',
                'email_verified_at' => NULL,
                'password' => '$2y$10$TpmangOqXni998vXYP.rx.qNckB0GPri1nwWn3iQ.77TEC94jXOBO',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-25 22:58:39',
                'updated_at' => '2025-06-25 22:58:59',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'uuid' => 'fd4687c8-b52c-49b4-9252-a35cd8039513',
                'user_type_id' => 2,
                'full_name' => 'হোসেন মাঝি',
                'user_name' => 'হোসেন মাঝি',
                'profile_image' => 'users/1750850062165.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'hossen@gmail.com',
                'contact_no' => '9656889990',
                'email_verified_at' => NULL,
                'password' => '$2y$10$HeVXe1Zy/y2LQCP8F..j.uWi2dK8HqcBP.rYIrBnUgqYwk7n./16K',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-25 23:13:02',
                'updated_at' => '2025-06-25 23:14:22',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'uuid' => 'b98a4fb2-e229-4abb-a852-82bdbb8c45c1',
                'user_type_id' => 2,
                'full_name' => 'জানিফ হাসান',
                'user_name' => 'জানিফ হাসান',
                'profile_image' => 'users/1750856193806.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'writer@bdtask.com',
                'contact_no' => '01500000000',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FyxkcRuESOQ10t7nJnvaROConyHQ.ja8zdtSoQckBMwpQjybOnJb2',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-26 00:54:52',
                'updated_at' => '2025-06-26 01:18:00',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'uuid' => 'dce3b397-49d5-4a4c-a684-835d355b86d6',
                'user_type_id' => 2,
                'full_name' => 'আয়ান তাহরিম',
                'user_name' => 'আয়ান তাহরিম',
                'profile_image' => 'users/1750856331608.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'writer1@bdtask.com',
                'contact_no' => '01500000001',
                'email_verified_at' => NULL,
                'password' => '$2y$10$FGU8TA5KUG1BLjC6Pp.9j.oUwXTHFfNjtJrWlBiqiQ1a3kxx3k37q',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-26 00:58:01',
                'updated_at' => '2025-06-26 01:19:02',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 10,
                'uuid' => 'db3be0d5-5493-4cbf-8701-4afa57d41c78',
                'user_type_id' => 2,
                'full_name' => 'তাসনিম ফারাহ',
                'user_name' => 'তাসনিম ফারাহ',
                'profile_image' => 'users/1750858426287.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'tasnim@bdtask.com',
                'contact_no' => '01500000003',
                'email_verified_at' => NULL,
                'password' => '$2y$10$IqlFS9AMmnSlCuAokc3LnONNOApjbfNyUKxIkvliFJ1WGQBVBlAvi',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-26 01:31:54',
                'updated_at' => '2025-06-26 01:33:46',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 11,
                'uuid' => 'f4a23780-f7e3-4732-918d-cfdc06cee195',
                'user_type_id' => 2,
                'full_name' => 'রিহান আলভি',
                'user_name' => 'রিহান আলভি',
                'profile_image' => 'users/1750858525700.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'rihan@bdtask.com',
                'contact_no' => '01500120000',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Uz3qN.YcM0bI65E78FppReTlpAyAzHtMs5i55Z5bVnDMPVKr9/7SS',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-26 01:34:50',
                'updated_at' => '2025-06-26 01:35:25',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 12,
                'uuid' => 'd7900cc3-a35f-4faf-a381-d7b98fb32a5a',
                'user_type_id' => 2,
                'full_name' => 'Mahidujjaman Tamim',
                'user_name' => 'তামিম রেহমান',
                'profile_image' => 'users/1751094738476.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'tamim@bdtask.com',
                'contact_no' => '01588888888',
                'email_verified_at' => NULL,
                'password' => '$2y$10$I2qLemofqHu/Z9GL4l11T.AD9l8z81w0Dn3IFO2DT3FchQu9J/fOG',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-28 19:11:04',
                'updated_at' => '2025-07-13 20:21:37',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 13,
                'uuid' => '5accea4d-a606-4ea8-90a6-da5e8901edd5',
                'user_type_id' => 2,
                'full_name' => 'sukumar barua',
                'user_name' => 'sukumar barua',
                'profile_image' => 'users/1751112326250.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'suku@gmail.com',
                'contact_no' => '5345345345',
                'email_verified_at' => NULL,
                'password' => '$2y$10$lJx87BaksSOPCUICPf.Y5e823Bxw9.j9W8UQBbKJCY0j.inpqgTeq',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-29 00:05:00',
                'updated_at' => '2025-06-29 00:05:26',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 14,
                'uuid' => '7e7a8e52-cc9a-470d-93ea-e889a33b6f4a',
                'user_type_id' => 2,
                'full_name' => 'أسماء بنت أبي بكر',
                'user_name' => 'أسماء بنت أبي بكر',
                'profile_image' => 'users/1751178432460.jpg',
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'js@gmail.com',
                'contact_no' => '575675675',
                'email_verified_at' => NULL,
                'password' => '$2y$10$snls1s5d/n3Vw//Qau3aGeiDJeTUXcii0UpjCN0CJNJ/RgsqEwbwu',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-06-29 18:19:59',
                'updated_at' => '2025-06-29 18:27:12',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 16,
                'uuid' => 'e767e541-d9f3-4e4a-ad87-2298a99bd832',
                'user_type_id' => 2,
                'full_name' => 'shadin khan',
                'user_name' => 'shadin khan',
                'profile_image' => NULL,
                'cover_image' => NULL,
                'signature' => NULL,
                'email' => 'shadin@bdtask.com',
                'contact_no' => '01222222255',
                'email_verified_at' => NULL,
                'password' => '$2y$10$GNmOVvC2YxSXJKfYEHwqZu1tshaJE.tXh8hEZCTIZj2WekmXdFIFO',
                'remember_token' => NULL,
                'attempt' => NULL,
                'recovery_code' => NULL,
                'is_active' => 1,
                'created_by' => NULL,
                'updated_by' => NULL,
                'created_at' => '2025-07-01 22:22:04',
                'updated_at' => '2025-07-01 22:22:04',
                'deleted_at' => NULL,
            ),
        ));
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}