<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoDataVideoNewsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('video_news')->truncate();
        
        DB::table('video_news')->insert(array (
            0 => 
            array (
                'id' => 18,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-05-13',
                'total_view' => 1261,
                'encode_title' => 'trevor-lawrance-to-throw-for-teams-sooner-than-expected',
                'title' => 'Trevor lawrance to throw for teams sooner than expected',
                'details' => '<p>Trevor lawrance to throw for teams sooner than expected</p>',
                'thumbnail_image' => 'videonews/thumb/1747568256220.png',
                'image_alt' => 'Image Alt',
                'image_title' => 'Image Title',
                'video' => 'videonews/video/1747046157252.mp4',
                'video_url' => NULL,
                'reference' => 'Reference',
                'meta_keyword' => 'Keyword',
                'meta_description' => 'Description',
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-05-12 16:35:57',
                'updated_at' => '2025-07-20 09:04:59',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 19,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-05-14',
                'total_view' => 0,
                'encode_title' => '',
                'title' => 'Test soft delete',
                'details' => '<p>Test soft delete Test soft delete.</p>',
                'thumbnail_image' => 'videonews/thumb/1747229286597.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => NULL,
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '0',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-05-14 19:26:04',
                'updated_at' => '2025-05-18 17:35:49',
                'deleted_at' => '2025-05-18 17:35:49',
            ),
            2 => 
            array (
                'id' => 20,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-05-15',
                'total_view' => 1122,
                'encode_title' => 'trevor-lawrance-to-throw-for-teams-sooner-than-expected-3',
                'title' => 'Trevor lawrance to throw for teams sooner than expected',
                'details' => '<p>Trevor lawrance to throw for teams sooner than expected</p>',
                'thumbnail_image' => 'videonews/thumb/1747562075899.png',
                'image_alt' => 'Image Alt',
                'image_title' => 'Image Title',
                'video' => '',
                'video_url' => NULL,
                'reference' => NULL,
                'meta_keyword' => 'title, test,new',
                'meta_description' => 'test title',
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-05-15 19:20:38',
                'updated_at' => '2025-07-20 10:57:10',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 21,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-05-18',
                'total_view' => 1,
                'encode_title' => 'trevor-lawrance-to-throw-for-teams-sooner-than-expected-2',
                'title' => 'Trevor lawrance to throw for teams sooner than expected',
                'details' => '<p><a href="http://localhost/news365_for_see_html_design/#">Trevor lawrance to throw for teams sooner than expected</a></p>',
                'thumbnail_image' => '',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => NULL,
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-05-18 17:38:00',
                'updated_at' => '2025-07-20 07:59:23',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 22,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-05-17',
                'total_view' => 1,
                'encode_title' => 'trevor-lawrance-to-throw-for-teams-sooner-than-expected-1',
                'title' => 'Trevor lawrance to throw for teams sooner than expected',
                'details' => '<p>Trevor lawrance to throw for teams sooner than expected</p>',
                'thumbnail_image' => 'videonews/thumb/1747568335238.png',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => NULL,
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-05-18 17:38:55',
                'updated_at' => '2025-07-20 05:53:46',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 23,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-05-19',
                'total_view' => 5126,
                'encode_title' => 'demonstrators-call-on-us-to-continue-to-support-ukraine-war-efforts-against-russia',
                'title' => 'Demonstrators Call on US to Continue to Support Ukraine War Efforts Against Russia',
                'details' => '<p>Demonstrators Call on US to Continue to Support Ukraine War Efforts Against Russia</p>',
                'thumbnail_image' => 'videonews/thumb/1747568366589.png',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => NULL,
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-05-18 17:39:26',
                'updated_at' => '2025-07-20 06:06:27',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 24,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-06-03',
                'total_view' => 14,
                'encode_title' => 'south-korea-election-results-2025-live-lee-jae-myung-projected-to-win',
                'title' => 'South Korea election results 2025 live: Lee Jae-myung projected to win',
                'details' => '<h1>South Korea election results 2025 live: Lee Jae-myung projected to win</h1>',
                'thumbnail_image' => 'videonews/thumb/1748959318549.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=2B6SbePVg8Y',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2025-06-03 20:01:58',
                'updated_at' => '2025-07-20 06:17:26',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 25,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-06-04',
                'total_view' => 25,
                'encode_title' => 'test-news-1',
                'title' => 'Why are India and Bangladesh clashing?',
                'details' => '<p>test news 1https://www.youtube.com/watch?v=i_2AZ69WkPY</p>',
                'thumbnail_image' => 'videonews/thumb/174930498913.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=i_2AZ69WkPY',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-06-05 03:51:50',
                'updated_at' => '2025-07-20 09:52:28',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 26,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-06-07',
                'total_view' => 19,
                'encode_title' => 'the-island-of-secrets-investigation-journalism',
                'title' => 'The Island of Secrets-Investigation Journalism',
                'details' => '<p>A remote Mauritian island is being quietly transformed into a military hub for India&#39;s navy. That&rsquo;s what we found using satellite pictures, shipping data, financial documents, and images from a barely accessible island about 1100 km north of Mauritius. The Island of Secrets also shows how the construction project on Agal&eacute;ga has the potential to uproot the lives of its 300 residents in order to make way for a military facility. Residents worry that what happened on the Mauritian island of Diego Garcia in the 1960s will happen to them. The Mauritian government responded to this film by restating its position that there is &ldquo;no agreement&rdquo; with India to set up a military a base in Agal&eacute;ga. It said that construction work on the island is designed to improve &ldquo;inadequate infrastructure facilities&rdquo;. The government also stated that it has no intention of displacing people living on the island. India&rsquo;s Ministry of Defence and Ministry of External Affairs did not respond to our request for comment.</p>',
                'thumbnail_image' => 'videonews/thumb/1749304318119.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=wKb1nZ5YnCg',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-06-08 01:50:20',
                'updated_at' => '2025-07-20 08:39:49',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 27,
                'language_id' => 1,
                'reporter_id' => 1,
                'publish_date' => '2025-06-07',
                'total_view' => 19,
                'encode_title' => 'rare-access-inside-one-of-the-worlds-longest-running-conflicts',
                'title' => 'Rare access inside one of the world’s longest running conflicts',
                'details' => '<p>In this film, we followed a whistleblower and a patriotic military commander who provided a visceral, yet intimate, insight into a nation caught between foreign-backed rebels and the government of then-president Joseph Kabila, who ruled until 2019. As the conflict resonates with both men&#39;s lives, the film, This is Congo, reveals the insidious legacy of colonialism, resource exploitation and wars that have created a continuing cycle of violence.</p>',
                'thumbnail_image' => 'videonews/thumb/1749304569593.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=De5cL_r0dQ4',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2025-06-08 01:56:09',
                'updated_at' => '2025-07-20 09:42:13',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 28,
                'language_id' => 3,
                'reporter_id' => 1,
                'publish_date' => '2025-06-07',
                'total_view' => 43,
                'encode_title' => 'inside-the-talibans-takeover-of-afghanistan-exclusive-access',
                'title' => 'Inside the Taliban\'s Takeover of Afghanistan - Exclusive access',
                'details' => '<p>&nbsp;</p>

<p>Inside the Taliban&#39;s Takeover of Afghanistan - Exclusive access adsdsad</p>',
                'thumbnail_image' => 'videonews/thumb/1749304755808.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=cyV-b0YL1C4',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-06-08 01:59:15',
                'updated_at' => '2025-07-20 16:44:07',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 29,
                'language_id' => 17,
                'reporter_id' => 6,
                'publish_date' => '2025-06-26',
                'total_view' => 7,
                'encode_title' => 'bannkbdler-banglades-taimlain-banglades-timeline-bangladesh',
                'title' => 'বাঁকবদলের বাংলাদেশ | টাইমলাইন বাংলাদেশ | Timeline Bangladesh',
                'details' => '<p>&nbsp;</p>

<p>ড. মির্জা গালিব, সহকারী অধ্যাপক, হাওয়ার্ড বিশ্ববিদ্যালয়, যুক্তরাষ্ট্র। রেজাউল করিম রনি, সম্পাদক, জবান। ডা. জাহেদ উর রহমান, বিশিষ্ট রাজনৈতিক বিশ্লেষক।<br />
&nbsp;</p>',
                'thumbnail_image' => 'videonews/thumb/1750948982300.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=UlT4u4Hrfic',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-06-27 02:41:39',
                'updated_at' => '2025-06-29 05:11:40',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 30,
                'language_id' => 17,
                'reporter_id' => 6,
                'publish_date' => '2025-06-28',
                'total_view' => 4,
                'encode_title' => 'analyzing-asias-greenest-and-least-green-metropolises-dw-news',
                'title' => 'Analyzing Asia\'s greenest and least green metropolises | DW News',
                'details' => '<p>Analyzing Asia&#39;s greenest and least green metropolises | DW News</p>',
                'thumbnail_image' => 'videonews/thumb/1751101480786.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=b4FigLAq0BI',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2025-06-28 21:04:40',
                'updated_at' => '2025-07-04 17:35:45',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 31,
                'language_id' => 17,
                'reporter_id' => 10,
                'publish_date' => '2025-06-28',
                'total_view' => 4,
                'encode_title' => 'srejmin-rohingoa-kzamp-bidroher-prstuti-niye-kee-jana-zacche-bbc-bangla',
                'title' => 'সরেজমিন রোহিঙ্গা ক্যাম্প: ‘বিদ্রোহের প্রস্তুতি’ নিয়ে কী জানা যাচ্ছে? BBC Bangla',
                'details' => '<h1>সরেজমিন রোহিঙ্গা ক্যাম্প: &lsquo;বিদ্রোহের প্রস্তুতি&rsquo; নিয়ে কী জানা যাচ্ছে? BBC Bangla</h1>

<p>&nbsp;</p>',
                'thumbnail_image' => 'videonews/thumb/1751102219576.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=uvf-VjRM2Wk',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-06-28 21:13:41',
                'updated_at' => '2025-07-07 16:47:57',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 32,
                'language_id' => 17,
                'reporter_id' => 9,
                'publish_date' => '2025-06-28',
                'total_view' => 8,
                'encode_title' => 'ken-uttr-koriyay-kkhno-sena-ovzutthan-hy-na-adzopant-why-north-korea-never-has-coups',
                'title' => 'কেন উত্তর কোরিয়ায় কখনো সেনা অভ্যুত্থান হয় না ?| আদ্যোপান্ত | Why North Korea Never Has Coups',
                'details' => '<h1>কেন উত্তর কোরিয়ায় কখনো সেনা অভ্যুত্থান হয় না ?| আদ্যোপান্ত | Why North Korea Never Has Coups</h1>

<p>&nbsp;</p>',
                'thumbnail_image' => 'videonews/thumb/1751102536739.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=PPUjMLzc8iM',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2025-06-28 21:22:16',
                'updated_at' => '2025-07-10 03:38:02',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 33,
                'language_id' => 17,
                'reporter_id' => 9,
                'publish_date' => '2025-06-28',
                'total_view' => 10,
                'encode_title' => 'kon-czalenj-mokabela-kre-parmanbik-sktidhr-banglades-roppur-nuclear-plant-uranium-news24',
                'title' => 'কোন চ্যালেঞ্জ মোকাবেলা করে পারমাণবিক শক্তিধর বাংলাদেশ? | Roppur Nuclear Plant | Uranium | News24',
                'details' => '<h1>কোন চ্যালেঞ্জ মোকাবেলা করে পারমাণবিক শক্তিধর বাংলাদেশ? | Roppur Nuclear Plant | Uranium | News24</h1>',
                'thumbnail_image' => 'videonews/thumb/1751102949723.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=pFPeokRz3E0',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-06-28 21:28:22',
                'updated_at' => '2025-07-10 22:35:13',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 34,
                'language_id' => 3,
                'reporter_id' => 12,
                'publish_date' => '2025-07-01',
                'total_view' => 1,
                'encode_title' => 'كيف-دخلنا-إلى-الشيشان-وهل-حقيقة-ممنوع-تصوير-هناك-ارض-الأبطال',
                'title' => 'كيف دخلنا إلى الشيشان وهل حقيقة ممنوع تصوير هناك 🇷🇺 ارض الأبطال',
                'details' => '<h1>كيف دخلنا إلى الشيشان وهل حقيقة ممنوع تصوير هناك 🇷🇺 ارض الأبطال</h1>

<p>&nbsp;</p>',
                'thumbnail_image' => 'videonews/thumb/1751361319343.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=_5joevRVwG8',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => NULL,
                'created_at' => '2025-07-01 21:15:19',
                'updated_at' => '2025-07-11 03:20:07',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 35,
                'language_id' => 3,
                'reporter_id' => 12,
                'publish_date' => '2025-07-01',
                'total_view' => 0,
                'encode_title' => 'هل-باعت-مصر-أرض-رأس-شقير-لسداد-ديونوما-هي-الصكوك-السيادية',
                'title' => 'هل باعت مصر أرض "رأس شقير" لسداد ديون…وما هي الصكوك السيادية؟',
                'details' => '<p>هل باعت مصر أرض &quot;رأس شقير&quot; لسداد ديون&hellip;وما هي الصكوك السيادية؟</p>',
                'thumbnail_image' => 'videonews/thumb/1751361690733.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=SAFQhrsXNQw',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-07-01 21:21:30',
                'updated_at' => '2025-07-19 03:53:23',
                'deleted_at' => '2025-07-19 03:53:23',
            ),
            18 => 
            array (
                'id' => 36,
                'language_id' => 3,
                'reporter_id' => 12,
                'publish_date' => '2025-07-01',
                'total_view' => 1,
                'encode_title' => 'بلاقيود-أمل-أبو-زيد-ترسيم-الحدود-مطلب-لبناني-والتطبيع-يحتاج-وفاقا-وطنيا',
                'title' => 'بلاقيود : أمل أبو زيد : ترسيم الحدود مطلب لبناني والتطبيع يحتاج وفاقًا وطنيًا',
                'details' => '<p data-end="353" data-start="159">أشعل مقطع فيديو نشره شاب عربي على تطبيق &quot;تيك توك&quot; مواقع التواصل الاجتماعي خلال الساعات الماضية، حيث ظهر فيه وهو يقدّم هدية مفاجئة لوالدته بمناسبة انتهاء دراسته الجامعية.</p>

<p data-end="635" data-start="355">الفيديو، الذي لم تتجاوز مدته 30 ثانية، حصد أكثر من 10 ملايين مشاهدة خلال يومين فقط، وانتشر بسرعة كبيرة على منصات &quot;إنستغرام&quot;، &quot;فيسبوك&quot;، و&quot;يوتيوب شورتس&quot;. وقد عبّر آلاف المتابعين عن إعجابهم وتأثرهم الشديد بالموقف، حيث ظهرت الأم وهي تبكي فرحاً بعد أن تلقت مفاتيح سيارة جديدة من ابنها.</p>

<p data-end="915" data-start="637"><strong data-end="679" data-start="637">تفاعل واسع ودعوات للإحسان إلى الوالدين</strong><br data-end="682" data-start="679" />
علق الكثير من المشاهير والمؤثرين على الفيديو، مشيدين بالمبادرة الطيبة التي قام بها الشاب، وكتب أحدهم: &quot;هذا هو الجيل الذي نفتخر به.. البرّ لا يُقدّر بثمن&quot;.<br data-end="839" data-start="836" />
كما أعادت صفحات إعلامية شهيرة نشر الفيديو، ما زاد من انتشاره بشكل غير مسبوق.</p>

<p data-end="1144" data-start="917"><strong data-end="933" data-start="917">رسالة الشاب:</strong><br data-end="936" data-start="933" />
في تعليق مرفق مع الفيديو، كتب الشاب: &quot;أقل ما يمكنني تقديمه لمن ضحت بكل شيء من أجلي. شكراً أمي&quot;. وأضاف لاحقاً في تصريح لموقع إخباري محلي: &quot;أردت فقط أن أُدخل السرور إلى قلبها، ولم أكن أتوقع هذا التفاعل الكبير&quot;.</p>

<p data-end="1306" data-start="1146"><strong data-end="1169" data-start="1146">دعوة للوعي الإنساني</strong><br data-end="1172" data-start="1169" />
وقد استغل بعض النشطاء هذا الحدث للدعوة إلى مزيد من التقدير للوالدين، والتأكيد على أهمية برهم في الحياة اليومية، وليس فقط في المناسبات.</p>

<hr data-end="1311" data-start="1308" />
<p data-end="1476" data-is-last-node="" data-is-only-node="" data-start="1313">&nbsp;</p>',
                'thumbnail_image' => 'videonews/thumb/1751361957803.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=uMJ0K9ykFhA',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-07-01 21:25:57',
                'updated_at' => '2025-07-19 03:53:17',
                'deleted_at' => '2025-07-19 03:53:17',
            ),
            19 => 
            array (
                'id' => 37,
                'language_id' => 3,
                'reporter_id' => 12,
                'publish_date' => '2025-07-01',
                'total_view' => 0,
                'encode_title' => 'شبكات-تهريب-النمل-قضية-تاريخية-في-كينيا-بطلها-شابان-بلجيكيان',
                'title' => 'شبكات | تهريب النمل.. قضية تاريخية في كينيا بطلها شابان بلجيكيان',
                'details' => '<p data-end="404" data-start="161">أعلنت مجموعة من الباحثين في المركز الوطني للبحث العلمي في فرنسا عن اكتشاف مذهل حول طريقة تواصل النمل داخل المستعمرات، واصفين النظام بأنه &quot;أشبه بشبكة واي فاي حيوية&quot; تعتمد على إشارات كيميائية دقيقة وسرعة استجابة خارقة.</p>

<p data-end="640" data-start="406">الدراسة التي نُشرت في مجلة <em data-end="456" data-start="433">Nature Communications</em> أظهرت أن النمل لا يعتمد فقط على الفيرومونات كما كان يعتقد سابقًا، بل يستخدم نمطاً معقداً من الإشارات الكيميائية والاهتزازات الأرضية يمكنه من نقل المعلومات بين آلاف الأفراد خلال ثوانٍ.</p>

<p data-end="879" data-start="642"><strong data-end="668" data-start="642">&quot;تنسيق مذهل بدون قائد&quot;</strong><br data-end="671" data-start="668" />
يقول الدكتور جون بيير، المشرف على الدراسة: &quot;رغم عدم وجود قائد مباشر للمستعمرة، إلا أن النمل يعمل بتناسق أشبه بالأنظمة الذكية في الروبوتات. كل نملة تعرف ما عليها فعله بناءً على إشارات محيطة غير مرئية للإنسان&quot;.</p>

<p data-end="1103" data-start="881"><strong data-end="903" data-start="881">فوائد محتملة للبشر</strong><br data-end="906" data-start="903" />
وقد أشار الباحثون إلى أن هذا النظام البيولوجي الفريد قد يُستخدم كمصدر إلهام لتطوير شبكات اتصالات بشرية أكثر فاعلية، خاصة في البيئات المعقدة أو الأماكن التي لا تتوفر فيها البنية التحتية التكنولوجية.</p>

<p data-end="1337" data-start="1105"><strong data-end="1125" data-start="1105">تطبيقات مستقبلية</strong><br data-end="1128" data-start="1125" />
علماء التكنولوجيا الحيوية والروبوتات يعملون حالياً على دراسة كيف يمكن تقليد هذا النظام في فرق الروبوتات التي تقوم بمهام في مناطق الكوارث أو العمليات العسكرية، حيث يلزم التنسيق دون الحاجة إلى اتصال مركزي مباشر.</p>

<p>&nbsp;</p>',
                'thumbnail_image' => 'videonews/thumb/175136212466.jpg',
                'image_alt' => NULL,
                'image_title' => NULL,
                'video' => '',
                'video_url' => 'https://www.youtube.com/watch?v=-i2mabbhVaA',
                'reference' => NULL,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'status' => '1',
                'created_by' => 1,
                'updated_by' => 1,
                'created_at' => '2025-07-01 21:28:44',
                'updated_at' => '2025-07-19 03:53:08',
                'deleted_at' => '2025-07-19 03:53:08',
            ),
        ));
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}