<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoDataMenuContentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('menu_contents')->truncate();
        
        DB::table('menu_contents')->insert(array (
            0 => 
            array (
                'id' => 1,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 55,
                'menu_position' => 12,
                'menu_level' => 'Life Style',
                'link_url' => NULL,
                'slug' => 'life-style',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-01 16:15:12',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            1 => 
            array (
                'id' => 2,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 57,
                'menu_position' => 14,
                'menu_level' => 'Fashion',
                'link_url' => NULL,
                'slug' => 'fashion',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-01 16:15:27',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            2 => 
            array (
                'id' => 3,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 56,
                'menu_position' => 13,
                'menu_level' => 'Travel',
                'link_url' => NULL,
                'slug' => 'travel',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-01 16:15:27',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            3 => 
            array (
                'id' => 4,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 58,
                'menu_position' => 16,
                'menu_level' => 'Quizzes',
                'link_url' => NULL,
                'slug' => 'quizzes',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-01 16:15:56',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            4 => 
            array (
                'id' => 5,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 51,
                'menu_position' => 4,
                'menu_level' => 'Business',
                'link_url' => NULL,
                'slug' => 'business',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-01 16:15:56',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            5 => 
            array (
                'id' => 6,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 11,
                'menu_position' => 15,
                'menu_level' => 'Sports',
                'link_url' => NULL,
                'slug' => 'sports',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-01 16:15:56',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            6 => 
            array (
                'id' => 7,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 61,
                'menu_position' => 11,
                'menu_level' => 'Recieps',
                'link_url' => NULL,
                'slug' => 'life-style-recieps',
                'parent_id' => 1,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-01 16:23:28',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            7 => 
            array (
                'id' => 8,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 60,
                'menu_position' => 10,
                'menu_level' => 'Design',
                'link_url' => NULL,
                'slug' => 'life-style-design',
                'parent_id' => 1,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-01 16:23:28',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            8 => 
            array (
                'id' => 9,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 59,
                'menu_position' => 8,
                'menu_level' => 'Photography',
                'link_url' => NULL,
                'slug' => 'life-style-photography',
                'parent_id' => 1,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-01 16:23:28',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            9 => 
            array (
                'id' => 10,
                'language_id' => 1,
                'content_type' => 'pages',
                'content_id' => 4,
                'menu_position' => 5,
                'menu_level' => 'Page with Sidebar',
                'link_url' => NULL,
                'slug' => 'page-with-sidebar',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-02 13:41:22',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            10 => 
            array (
                'id' => 13,
                'language_id' => 1,
                'content_type' => 'links',
                'content_id' => NULL,
                'menu_position' => 9,
                'menu_level' => 'News365 Application',
                'link_url' => 'https://codecanyon.net/item/news365-php-newspaper-magazine-blog-php-script-with-video-newspaper/19015501',
                'slug' => NULL,
                'parent_id' => 15,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-02 14:27:03',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            11 => 
            array (
                'id' => 15,
                'language_id' => 1,
                'content_type' => 'pages',
                'content_id' => 5,
                'menu_position' => 6,
                'menu_level' => 'External Links',
                'link_url' => NULL,
                'slug' => 'external-links',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-02 14:39:05',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            12 => 
            array (
                'id' => 19,
                'language_id' => 1,
                'content_type' => 'pages',
                'content_id' => 3,
                'menu_position' => 1,
                'menu_level' => 'Terms & Condition',
                'link_url' => NULL,
                'slug' => 'terms-condition',
                'parent_id' => NULL,
                'menu_id' => 4,
                'status' => 1,
                'created_at' => '2025-06-04 19:57:06',
                'updated_at' => '2025-07-10 23:26:47',
            ),
            13 => 
            array (
                'id' => 23,
                'language_id' => 1,
                'content_type' => 'links',
                'content_id' => 4,
                'menu_position' => 7,
                'menu_level' => 'Bdtask Website',
                'link_url' => 'https://bdtask.com',
                'slug' => NULL,
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-20 02:01:25',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            14 => 
            array (
                'id' => 24,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 62,
                'menu_position' => 5,
                'menu_level' => 'রাজনীতি',
                'link_url' => NULL,
                'slug' => 'rajniti',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-25 21:38:22',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            15 => 
            array (
                'id' => 25,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 63,
                'menu_position' => 6,
                'menu_level' => 'আন্তর্জাতিক',
                'link_url' => NULL,
                'slug' => 'internationalnews',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-25 21:38:48',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            16 => 
            array (
                'id' => 26,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 69,
                'menu_position' => 8,
                'menu_level' => 'লাইফস্টাইল',
                'link_url' => NULL,
                'slug' => 'lifestyle-news',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-25 21:38:59',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            17 => 
            array (
                'id' => 27,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 66,
                'menu_position' => 9,
                'menu_level' => 'স্বাস্থ্য',
                'link_url' => NULL,
                'slug' => 'health-news',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-25 21:39:08',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            18 => 
            array (
                'id' => 28,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 67,
                'menu_position' => 10,
                'menu_level' => 'প্রযুক্তি',
                'link_url' => NULL,
                'slug' => 'projukti',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-25 21:39:29',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            19 => 
            array (
                'id' => 29,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 68,
                'menu_position' => 11,
                'menu_level' => 'শিক্ষা',
                'link_url' => NULL,
                'slug' => 'education-news',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-25 21:39:43',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            20 => 
            array (
                'id' => 30,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 71,
                'menu_position' => 12,
                'menu_level' => 'পরিবেশ ও জলবায়ু',
                'link_url' => NULL,
                'slug' => 'climate-news',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-25 21:39:52',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            21 => 
            array (
                'id' => 31,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 70,
                'menu_position' => 13,
                'menu_level' => 'অপরাধ',
                'link_url' => NULL,
                'slug' => 'oporadh',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-25 21:39:52',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            22 => 
            array (
                'id' => 32,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 72,
                'menu_position' => 14,
                'menu_level' => 'মতামত',
                'link_url' => NULL,
                'slug' => 'motamot',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-25 21:41:35',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            23 => 
            array (
                'id' => 33,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 68,
                'menu_position' => 1,
                'menu_level' => 'শিক্ষা',
                'link_url' => NULL,
                'slug' => 'education-news',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-06-25 23:08:21',
                'updated_at' => '2025-07-15 17:38:26',
            ),
            24 => 
            array (
                'id' => 34,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 67,
                'menu_position' => 2,
                'menu_level' => 'প্রযুক্তি',
                'link_url' => NULL,
                'slug' => 'projukti',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-06-25 23:08:21',
                'updated_at' => '2025-07-15 17:38:26',
            ),
            25 => 
            array (
                'id' => 35,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 66,
                'menu_position' => 3,
                'menu_level' => 'স্বাস্থ্য',
                'link_url' => NULL,
                'slug' => 'health-news',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-06-25 23:08:21',
                'updated_at' => '2025-07-15 17:38:26',
            ),
            26 => 
            array (
                'id' => 36,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 65,
                'menu_position' => 4,
                'menu_level' => 'খেলা',
                'link_url' => NULL,
                'slug' => 'khela',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-06-25 23:08:21',
                'updated_at' => '2025-07-15 17:38:26',
            ),
            27 => 
            array (
                'id' => 37,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 64,
                'menu_position' => 5,
                'menu_level' => 'অর্থনীতি',
                'link_url' => NULL,
                'slug' => 'economy',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-06-25 23:08:21',
                'updated_at' => '2025-07-15 17:38:26',
            ),
            28 => 
            array (
                'id' => 38,
                'language_id' => 3,
                'content_type' => 'categories',
                'content_id' => 85,
                'menu_position' => 9,
                'menu_level' => 'المنوعات والترفيه',
                'link_url' => NULL,
                'slug' => 'lifestyle',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-26 19:44:44',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            29 => 
            array (
                'id' => 39,
                'language_id' => 3,
                'content_type' => 'categories',
                'content_id' => 84,
                'menu_position' => 10,
                'menu_level' => 'الرأي والمقالات',
                'link_url' => NULL,
                'slug' => 'opinion-ar',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-26 19:44:44',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            30 => 
            array (
                'id' => 40,
                'language_id' => 3,
                'content_type' => 'categories',
                'content_id' => 83,
                'menu_position' => 8,
                'menu_level' => 'العلوم والتكنولوجيا',
                'link_url' => NULL,
                'slug' => 'science-ar',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-26 19:44:44',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            31 => 
            array (
                'id' => 41,
                'language_id' => 3,
                'content_type' => 'categories',
                'content_id' => 82,
                'menu_position' => 7,
                'menu_level' => 'الثقافة والفنون',
                'link_url' => NULL,
                'slug' => 'culture-ar',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-26 19:44:44',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            32 => 
            array (
                'id' => 43,
                'language_id' => 3,
                'content_type' => 'categories',
                'content_id' => 80,
                'menu_position' => 5,
                'menu_level' => 'الاقتصاد والأعمال',
                'link_url' => NULL,
                'slug' => 'economy-ar',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-26 19:44:44',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            33 => 
            array (
                'id' => 44,
                'language_id' => 3,
                'content_type' => 'categories',
                'content_id' => 79,
                'menu_position' => 4,
                'menu_level' => 'السياسة',
                'link_url' => NULL,
                'slug' => 'politics-ar',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-26 19:44:44',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            34 => 
            array (
                'id' => 45,
                'language_id' => 3,
                'content_type' => 'categories',
                'content_id' => 78,
                'menu_position' => 3,
                'menu_level' => 'الأخبار الدولية',
                'link_url' => NULL,
                'slug' => 'international-ar',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-26 19:44:44',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            35 => 
            array (
                'id' => 46,
                'language_id' => 3,
                'content_type' => 'categories',
                'content_id' => 77,
                'menu_position' => 2,
                'menu_level' => 'الأخبار المحلية',
                'link_url' => NULL,
                'slug' => 'local-news-ar',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-26 19:44:44',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            36 => 
            array (
                'id' => 47,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 65,
                'menu_position' => 7,
                'menu_level' => 'খেলা',
                'link_url' => NULL,
                'slug' => 'khela',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-29 00:57:35',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            37 => 
            array (
                'id' => 52,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 71,
                'menu_position' => 2,
                'menu_level' => 'কৃষি ও জলবায়ু',
                'link_url' => NULL,
                'slug' => 'climate-news',
                'parent_id' => NULL,
                'menu_id' => 3,
                'status' => 1,
                'created_at' => '2025-06-29 01:30:22',
                'updated_at' => '2025-07-15 17:26:16',
            ),
            38 => 
            array (
                'id' => 53,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 69,
                'menu_position' => 3,
                'menu_level' => 'লাইফস্টাইল',
                'link_url' => NULL,
                'slug' => 'lifestyle-news',
                'parent_id' => NULL,
                'menu_id' => 3,
                'status' => 1,
                'created_at' => '2025-06-29 01:30:22',
                'updated_at' => '2025-07-15 17:26:16',
            ),
            39 => 
            array (
                'id' => 54,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 68,
                'menu_position' => 4,
                'menu_level' => 'শিক্ষা',
                'link_url' => NULL,
                'slug' => 'education-news',
                'parent_id' => NULL,
                'menu_id' => 3,
                'status' => 1,
                'created_at' => '2025-06-29 01:30:22',
                'updated_at' => '2025-07-15 17:26:16',
            ),
            40 => 
            array (
                'id' => 55,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 67,
                'menu_position' => 5,
                'menu_level' => 'প্রযুক্তি',
                'link_url' => NULL,
                'slug' => 'projukti',
                'parent_id' => NULL,
                'menu_id' => 3,
                'status' => 1,
                'created_at' => '2025-06-29 01:30:22',
                'updated_at' => '2025-07-15 17:26:16',
            ),
            41 => 
            array (
                'id' => 56,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 66,
                'menu_position' => 6,
                'menu_level' => 'স্বাস্থ্য',
                'link_url' => NULL,
                'slug' => 'health-news',
                'parent_id' => NULL,
                'menu_id' => 3,
                'status' => 1,
                'created_at' => '2025-06-29 01:30:22',
                'updated_at' => '2025-07-15 17:26:16',
            ),
            42 => 
            array (
                'id' => 57,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 48,
                'menu_position' => 3,
                'menu_level' => 'International News',
                'link_url' => NULL,
                'slug' => 'international-news',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-29 01:37:56',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            43 => 
            array (
                'id' => 58,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 45,
                'menu_position' => 1,
                'menu_level' => 'Politics',
                'link_url' => NULL,
                'slug' => 'politics',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-29 01:37:56',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            44 => 
            array (
                'id' => 59,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 76,
                'menu_position' => 4,
                'menu_level' => 'অন্যান্য খেলা',
                'link_url' => NULL,
                'slug' => 'other-sports-news',
                'parent_id' => 47,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-29 01:41:11',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            45 => 
            array (
                'id' => 60,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 75,
                'menu_position' => 3,
                'menu_level' => 'হকি',
                'link_url' => NULL,
                'slug' => 'hocky-news',
                'parent_id' => 47,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-29 01:41:11',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            46 => 
            array (
                'id' => 61,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 74,
                'menu_position' => 2,
                'menu_level' => 'ফুটবল',
                'link_url' => NULL,
                'slug' => 'football-news',
                'parent_id' => 47,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-29 01:41:11',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            47 => 
            array (
                'id' => 62,
                'language_id' => 17,
                'content_type' => 'categories',
                'content_id' => 73,
                'menu_position' => 1,
                'menu_level' => 'ক্রিকেট',
                'link_url' => NULL,
                'slug' => 'cricket-news',
                'parent_id' => 47,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-29 01:41:11',
                'updated_at' => '2025-06-29 01:42:40',
            ),
            48 => 
            array (
                'id' => 63,
                'language_id' => 3,
                'content_type' => 'categories',
                'content_id' => 54,
                'menu_position' => 6,
                'menu_level' => 'رياضة',
                'link_url' => NULL,
                'slug' => 'sport',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-06-29 18:37:47',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            49 => 
            array (
                'id' => 64,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 89,
                'menu_position' => 5,
                'menu_level' => 'Agriculture',
                'link_url' => NULL,
                'slug' => 'agriculture',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:18:32',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            50 => 
            array (
                'id' => 65,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 87,
                'menu_position' => 6,
                'menu_level' => 'Food',
                'link_url' => NULL,
                'slug' => 'food-news',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:18:32',
                'updated_at' => '2025-07-16 18:57:58',
            ),
            51 => 
            array (
                'id' => 66,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 57,
                'menu_position' => 7,
                'menu_level' => 'Fashion',
                'link_url' => NULL,
                'slug' => 'fashion',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:18:32',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            52 => 
            array (
                'id' => 67,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 55,
                'menu_position' => 8,
                'menu_level' => 'Life Style',
                'link_url' => NULL,
                'slug' => 'life-style',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:18:32',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            53 => 
            array (
                'id' => 68,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 45,
                'menu_position' => 9,
                'menu_level' => 'Politics',
                'link_url' => NULL,
                'slug' => 'politics',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:18:32',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            54 => 
            array (
                'id' => 69,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 11,
                'menu_position' => 10,
                'menu_level' => 'Sports',
                'link_url' => NULL,
                'slug' => 'sports',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:18:32',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            55 => 
            array (
                'id' => 70,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 86,
                'menu_position' => 1,
                'menu_level' => 'Crime',
                'link_url' => NULL,
                'slug' => 'crime-news',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:19:04',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            56 => 
            array (
                'id' => 71,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 56,
                'menu_position' => 2,
                'menu_level' => 'Travel',
                'link_url' => NULL,
                'slug' => 'travel',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:19:04',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            57 => 
            array (
                'id' => 72,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 51,
                'menu_position' => 3,
                'menu_level' => 'Business',
                'link_url' => NULL,
                'slug' => 'business',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:19:04',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            58 => 
            array (
                'id' => 73,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 18,
                'menu_position' => 4,
                'menu_level' => 'Health',
                'link_url' => NULL,
                'slug' => 'health',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-10 23:19:04',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            59 => 
            array (
                'id' => 74,
                'language_id' => 1,
                'content_type' => 'pages',
                'content_id' => 6,
                'menu_position' => 2,
                'menu_level' => 'Privacy Policy',
                'link_url' => NULL,
                'slug' => 'privacy-policy',
                'parent_id' => NULL,
                'menu_id' => 4,
                'status' => 1,
                'created_at' => '2025-07-10 23:26:40',
                'updated_at' => '2025-07-10 23:26:47',
            ),
            60 => 
            array (
                'id' => 75,
                'language_id' => 1,
                'content_type' => 'links',
                'content_id' => 5,
                'menu_position' => 5,
                'menu_level' => 'Promotion',
                'link_url' => '#',
                'slug' => NULL,
                'parent_id' => NULL,
                'menu_id' => 3,
                'status' => 1,
                'created_at' => '2025-07-10 23:28:21',
                'updated_at' => '2025-07-15 17:21:16',
            ),
            61 => 
            array (
                'id' => 76,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 88,
                'menu_position' => 2,
                'menu_level' => 'Social Media',
                'link_url' => NULL,
                'slug' => 'social-media',
                'parent_id' => NULL,
                'menu_id' => 3,
                'status' => 1,
                'created_at' => '2025-07-10 23:30:28',
                'updated_at' => '2025-07-15 17:21:16',
            ),
            62 => 
            array (
                'id' => 77,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 52,
                'menu_position' => 3,
                'menu_level' => 'Stock Market',
                'link_url' => NULL,
                'slug' => 'stock-market',
                'parent_id' => NULL,
                'menu_id' => 3,
                'status' => 1,
                'created_at' => '2025-07-10 23:30:28',
                'updated_at' => '2025-07-15 17:21:16',
            ),
            63 => 
            array (
                'id' => 78,
                'language_id' => 1,
                'content_type' => 'categories',
                'content_id' => 47,
                'menu_position' => 4,
                'menu_level' => 'Social Issues',
                'link_url' => NULL,
                'slug' => 'social-issues',
                'parent_id' => NULL,
                'menu_id' => 3,
                'status' => 1,
                'created_at' => '2025-07-10 23:30:28',
                'updated_at' => '2025-07-15 17:21:16',
            ),
            64 => 
            array (
                'id' => 79,
                'language_id' => 1,
                'content_type' => 'archive',
                'content_id' => 1,
                'menu_position' => 2,
                'menu_level' => 'Archive',
                'link_url' => NULL,
                'slug' => 'archive',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-07-14 17:06:37',
                'updated_at' => '2025-07-14 18:07:05',
            ),
            65 => 
            array (
                'id' => 80,
                'language_id' => 3,
                'content_type' => 'archive',
                'content_id' => 1,
                'menu_position' => 1,
                'menu_level' => 'Archive',
                'link_url' => NULL,
                'slug' => 'archive',
                'parent_id' => NULL,
                'menu_id' => 1,
                'status' => 1,
                'created_at' => '2025-07-14 17:12:38',
                'updated_at' => '2025-07-14 17:38:36',
            ),
            66 => 
            array (
                'id' => 81,
                'language_id' => 1,
                'content_type' => 'archive',
                'content_id' => 1,
                'menu_position' => 11,
                'menu_level' => 'Archive',
                'link_url' => NULL,
                'slug' => 'archive',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-14 17:39:17',
                'updated_at' => '2025-07-14 17:40:21',
            ),
            67 => 
            array (
                'id' => 88,
                'language_id' => 17,
                'content_type' => 'archive',
                'content_id' => 1,
                'menu_position' => 6,
                'menu_level' => 'আর্কাইভ',
                'link_url' => NULL,
                'slug' => 'archive',
                'parent_id' => NULL,
                'menu_id' => 2,
                'status' => 1,
                'created_at' => '2025-07-15 17:37:38',
                'updated_at' => '2025-07-15 17:38:26',
            ),
        ));
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}