<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DemoDataCategoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        DB::table('categories')->truncate();
        
        DB::table('categories')->insert(array (
            0 => 
            array (
                'id' => 11,
                'uuid' => '16ef12c7-fe98-4df9-b198-8ef1a167de9b',
                'category_id' => 11,
                'category_name' => 'Sports',
                'slug' => 'sports',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => 'category/1746351449102.png',
                'img_status' => 0,
                'category_type' => 1,
                'description' => 'Sports',
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-04 15:37:29',
                'updated_at' => '2025-05-04 15:39:15',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 18,
                'uuid' => 'c5979f8e-f420-4e8a-a3c6-542b042e8a06',
                'category_id' => 18,
                'category_name' => 'Health',
                'slug' => 'health',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => 'category/1746353006136.png',
                'img_status' => 0,
                'category_type' => 1,
                'description' => 'Health',
                'created_by' => 2,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#3B82F6',
                'created_at' => '2025-05-04 16:03:26',
                'updated_at' => '2025-05-19 15:36:19',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 36,
                'uuid' => '9752c2b9-a2bf-48d5-a33d-f289b82d88ab',
                'category_id' => 36,
                'category_name' => 'Topic',
                'slug' => 'topic',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => 'category/1746968967482.png',
                'img_status' => 0,
                'category_type' => 2,
                'description' => 'This is topic',
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => 'Meta key',
                'meta_description' => 'Meta description',
                'color_code' => '#3B82F6',
                'created_at' => '2025-05-06 12:01:54',
                'updated_at' => '2025-05-19 15:36:11',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 39,
                'uuid' => '51da6118-468d-43fe-85da-1bfdea49b484',
                'category_id' => 39,
                'category_name' => 'الرياضة',
                'slug' => 'الرياضة',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 1,
                'category_type' => 1,
                'description' => 'الرياضة',
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => 'الرياضة',
                'meta_description' => 'الرياضة',
                'color_code' => '#000000',
                'created_at' => '2025-05-11 19:11:48',
                'updated_at' => '2025-07-21 02:36:00',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 40,
                'uuid' => '992438f5-adce-4e31-9320-fb7f78327224',
                'category_id' => 40,
                'category_name' => 'الكريكيت',
                'slug' => 'الكريكيت-الرياضة',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '39',
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => 'الكريكيت الرياضة',
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => 'الكريكيت الرياضة',
                'meta_description' => 'الكريكيت الرياضة',
                'color_code' => '#000000',
                'created_at' => '2025-05-11 19:13:08',
                'updated_at' => '2025-05-11 19:13:08',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 41,
                'uuid' => '4ab9b4eb-87e7-4db0-a435-919a43daef79',
                'category_id' => 41,
                'category_name' => 'Cricket',
                'slug' => 'sports-cricket',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '11',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => 'Sports Cricket',
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => 'Cricket',
                'meta_description' => 'Sports Cricket',
                'color_code' => '#000000',
                'created_at' => '2025-05-11 19:13:52',
                'updated_at' => '2025-05-11 19:51:02',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 42,
                'uuid' => 'd2cc639d-2c35-4ba6-9fe6-716eec7ec4bd',
                'category_id' => 42,
                'category_name' => 'Football',
                'slug' => 'sports-football',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '11',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => 'Sports Football',
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => 'Football',
                'meta_description' => 'Sports Football',
                'color_code' => '#5d0c88',
                'created_at' => '2025-05-11 19:53:53',
                'updated_at' => '2025-05-14 18:09:57',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 44,
                'uuid' => 'b5ad84b9-34f6-436c-95cd-5391e22f3b70',
                'category_id' => 44,
                'category_name' => 'Weather',
                'slug' => 'weather',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-15 18:56:37',
                'updated_at' => '2025-05-20 10:47:42',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 45,
                'uuid' => 'b83ae1e1-004e-4272-80c1-c88584dab0cf',
                'category_id' => 45,
                'category_name' => 'Politics',
                'slug' => 'politics',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => 'Politics',
                'meta_description' => 'Politics',
                'color_code' => '#3d51b3',
                'created_at' => '2025-05-19 10:30:36',
                'updated_at' => '2025-07-21 01:31:06',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 46,
                'uuid' => '829e12b1-e318-41ce-b33e-8b22a2c54f05',
                'category_id' => 46,
                'category_name' => 'Government Policies',
                'slug' => 'government-policies',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '45',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#c63939',
                'created_at' => '2025-05-20 10:43:56',
                'updated_at' => '2025-07-21 01:28:09',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 47,
                'uuid' => '2578900f-0425-4fba-bb1e-c85e89b1e8b3',
                'category_id' => 47,
                'category_name' => 'Social Issues',
                'slug' => 'social-issues',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '45',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-20 10:44:24',
                'updated_at' => '2025-05-20 10:44:24',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 48,
                'uuid' => 'c597e7c4-5341-440c-b326-1df266c1e3e7',
                'category_id' => 48,
                'category_name' => 'International News',
                'slug' => 'international-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-20 10:44:56',
                'updated_at' => '2025-05-20 10:44:56',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 49,
                'uuid' => '3de882ed-0edf-4096-a795-9f25bfef3d77',
                'category_id' => 49,
                'category_name' => 'Global Politics',
                'slug' => 'global-politics',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '48',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-20 10:45:24',
                'updated_at' => '2025-07-21 01:31:01',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 50,
                'uuid' => 'f47281f4-d572-4c54-bdc0-00b2caa4fe98',
                'category_id' => 50,
                'category_name' => 'World Economy',
                'slug' => 'world-economy',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '48',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-20 10:45:52',
                'updated_at' => '2025-07-21 01:30:58',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 51,
                'uuid' => '41b709b9-ed35-4608-8d83-d5ce35a1e631',
                'category_id' => 51,
                'category_name' => 'Business',
                'slug' => 'business',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-20 10:46:09',
                'updated_at' => '2025-05-20 10:46:09',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 52,
                'uuid' => '31156933-8325-41f2-b22a-8ab55f21077c',
                'category_id' => 52,
                'category_name' => 'Stock Market',
                'slug' => 'stock-market',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '51',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-20 10:46:31',
                'updated_at' => '2025-05-20 10:46:31',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 53,
                'uuid' => '9032ebe1-306e-4a18-9912-90749dabf306',
                'category_id' => 53,
                'category_name' => 'Real Estate',
                'slug' => 'real-estate',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '51',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-20 10:46:48',
                'updated_at' => '2025-05-20 10:46:48',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 54,
                'uuid' => '641d29cd-ad11-4b2f-8b35-2b430dc5e126',
                'category_id' => 54,
                'category_name' => 'رياضة',
                'slug' => 'sport',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-05-26 15:25:22',
                'updated_at' => '2025-05-26 15:25:22',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 55,
                'uuid' => '5b8faa79-717d-44b4-8ca2-7c6f58e18b79',
                'category_id' => 55,
                'category_name' => 'Life Style',
                'slug' => 'life-style',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-01 16:12:15',
                'updated_at' => '2025-06-01 16:12:15',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 56,
                'uuid' => '84d6b08f-ef1d-4a3b-804c-59bc4345d3d7',
                'category_id' => 56,
                'category_name' => 'Travel',
                'slug' => 'travel',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-01 16:12:51',
                'updated_at' => '2025-06-01 16:12:51',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 57,
                'uuid' => '8594136a-e0bd-464b-9a42-76b3963f18ab',
                'category_id' => 57,
                'category_name' => 'Fashion',
                'slug' => 'fashion',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-01 16:13:37',
                'updated_at' => '2025-06-01 16:13:37',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 58,
                'uuid' => 'fe004fc5-85b7-4b9a-83a3-ce20c796fc34',
                'category_id' => 58,
                'category_name' => 'Quizzes',
                'slug' => 'quizzes',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 1,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-01 16:14:38',
                'updated_at' => '2025-06-29 18:43:47',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 59,
                'uuid' => '262dc77d-d1d2-478c-876a-393d336c4117',
                'category_id' => 59,
                'category_name' => 'Photography',
                'slug' => 'life-style-photography',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '55',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-01 16:21:17',
                'updated_at' => '2025-06-01 16:21:17',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 60,
                'uuid' => '3ae3417f-e335-4eb9-b11f-8a71ed4f2a5f',
                'category_id' => 60,
                'category_name' => 'Design',
                'slug' => 'life-style-design',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '55',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-01 16:21:54',
                'updated_at' => '2025-06-01 16:21:54',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 61,
                'uuid' => '76209c39-9771-4653-9eee-5b7eca0eede7',
                'category_id' => 61,
                'category_name' => 'Recieps',
                'slug' => 'life-style-recieps',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '55',
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-01 16:22:39',
                'updated_at' => '2025-06-01 16:22:39',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 62,
                'uuid' => 'f95c26ee-19b7-4a2a-9f2e-c39afffc559a',
                'category_id' => 62,
                'category_name' => 'রাজনীতি',
                'slug' => 'rajniti',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:32:34',
                'updated_at' => '2025-06-25 21:32:34',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 63,
                'uuid' => '5eda180b-969f-435c-be17-60daf5370889',
                'category_id' => 63,
                'category_name' => 'আন্তর্জাতিক',
                'slug' => 'internationalnews',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:33:17',
                'updated_at' => '2025-06-25 21:33:17',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 64,
                'uuid' => 'de87880e-9e24-49bc-9ec9-3a9d982b9d48',
                'category_id' => 64,
                'category_name' => 'অর্থনীতি',
                'slug' => 'economy',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:33:58',
                'updated_at' => '2025-06-25 22:56:00',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 65,
                'uuid' => '50f4ac31-2336-4a45-8719-43d59b876a46',
                'category_id' => 65,
                'category_name' => 'খেলা',
                'slug' => 'khela',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:34:25',
                'updated_at' => '2025-06-25 22:56:12',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 66,
                'uuid' => '06e089ed-3cae-4fe7-96c5-d19445a731e4',
                'category_id' => 66,
                'category_name' => 'স্বাস্থ্য',
                'slug' => 'health-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:34:51',
                'updated_at' => '2025-06-25 21:34:51',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 67,
                'uuid' => 'cc40b8af-cc84-45c3-9e1d-f28102ee48df',
                'category_id' => 67,
                'category_name' => 'প্রযুক্তি',
                'slug' => 'projukti',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:35:19',
                'updated_at' => '2025-06-25 21:35:19',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 68,
                'uuid' => '7fa054b3-45d1-4dee-ab72-518927824743',
                'category_id' => 68,
                'category_name' => 'শিক্ষা',
                'slug' => 'education-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:35:52',
                'updated_at' => '2025-06-25 21:35:52',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 69,
                'uuid' => 'f4b44528-4282-4478-8303-48412c2bcd48',
                'category_id' => 69,
                'category_name' => 'লাইফস্টাইল',
                'slug' => 'lifestyle-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:36:23',
                'updated_at' => '2025-06-25 21:36:23',
                'deleted_at' => NULL,
            ),
            33 => 
            array (
                'id' => 70,
                'uuid' => '4f6cc0fd-98c3-457f-8725-72bae080bd2a',
                'category_id' => 70,
                'category_name' => 'অপরাধ',
                'slug' => 'oporadh',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:36:48',
                'updated_at' => '2025-06-25 21:36:48',
                'deleted_at' => NULL,
            ),
            34 => 
            array (
                'id' => 71,
                'uuid' => '0d14b7e0-eeee-49c5-bfe5-a64f6bd9e4ff',
                'category_id' => 71,
                'category_name' => 'কৃষি ও জলবায়ু',
                'slug' => 'climate-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:37:47',
                'updated_at' => '2025-06-29 00:21:47',
                'deleted_at' => NULL,
            ),
            35 => 
            array (
                'id' => 72,
                'uuid' => '74a8f47e-11db-40e3-8198-38eb4eb52c35',
                'category_id' => 72,
                'category_name' => 'মতামত',
                'slug' => 'motamot',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-25 21:41:15',
                'updated_at' => '2025-06-25 21:41:15',
                'deleted_at' => NULL,
            ),
            36 => 
            array (
                'id' => 73,
                'uuid' => '1c8a5573-4043-4596-8f39-a4e8b8e78e5f',
                'category_id' => 73,
                'category_name' => 'ক্রিকেট',
                'slug' => 'cricket-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '65',
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 18:16:10',
                'updated_at' => '2025-06-26 18:16:10',
                'deleted_at' => NULL,
            ),
            37 => 
            array (
                'id' => 74,
                'uuid' => 'd0f39f8c-3e1a-4f6d-a557-0b8b67c6ca2c',
                'category_id' => 74,
                'category_name' => 'ফুটবল',
                'slug' => 'football-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '65',
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 18:16:38',
                'updated_at' => '2025-06-26 18:16:38',
                'deleted_at' => NULL,
            ),
            38 => 
            array (
                'id' => 75,
                'uuid' => 'ae28313a-6f21-485c-9576-411c32738724',
                'category_id' => 75,
                'category_name' => 'হকি',
                'slug' => 'hocky-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '65',
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 18:17:30',
                'updated_at' => '2025-06-26 18:17:30',
                'deleted_at' => NULL,
            ),
            39 => 
            array (
                'id' => 76,
                'uuid' => '2f96b217-a544-43fc-9c96-10cdedb5046a',
                'category_id' => 76,
                'category_name' => 'অন্যান্য খেলা',
                'slug' => 'other-sports-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '65',
                'language_id' => 17,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 18:18:25',
                'updated_at' => '2025-06-26 18:18:25',
                'deleted_at' => NULL,
            ),
            40 => 
            array (
                'id' => 77,
                'uuid' => 'bba895e6-580c-4ece-a3c3-534bba94f237',
                'category_id' => 77,
                'category_name' => 'الأخبار المحلية',
                'slug' => 'local-news-ar',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 19:39:51',
                'updated_at' => '2025-06-26 19:39:51',
                'deleted_at' => NULL,
            ),
            41 => 
            array (
                'id' => 78,
                'uuid' => '7f69ecd9-1d2e-41e9-bf83-f07a2df323ef',
                'category_id' => 78,
                'category_name' => 'الأخبار الدولية',
                'slug' => 'international-ar',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 19:40:20',
                'updated_at' => '2025-06-26 19:40:20',
                'deleted_at' => NULL,
            ),
            42 => 
            array (
                'id' => 79,
                'uuid' => '947fa31a-e0c3-4ae9-8e6f-9a72d0b09bbd',
                'category_id' => 79,
                'category_name' => 'السياسة',
                'slug' => 'politics-ar',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 19:40:41',
                'updated_at' => '2025-06-26 19:40:41',
                'deleted_at' => NULL,
            ),
            43 => 
            array (
                'id' => 80,
                'uuid' => 'deb8e38c-4978-428a-b67b-77e22352449b',
                'category_id' => 80,
                'category_name' => 'الاقتصاد والأعمال',
                'slug' => 'economy-ar',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 19:41:07',
                'updated_at' => '2025-06-26 19:41:07',
                'deleted_at' => NULL,
            ),
            44 => 
            array (
                'id' => 81,
                'uuid' => '4797bcc9-7b09-4a26-ba88-24b89033adf5',
                'category_id' => 81,
                'category_name' => 'الرياضة',
                'slug' => 'sports-ar',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 19:41:34',
                'updated_at' => '2025-07-21 02:35:39',
                'deleted_at' => NULL,
            ),
            45 => 
            array (
                'id' => 82,
                'uuid' => '802985c2-f7ff-440f-97e6-27cc7c42fcb8',
                'category_id' => 82,
                'category_name' => 'الثقافة والفنون',
                'slug' => 'culture-ar',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 19:41:58',
                'updated_at' => '2025-06-26 19:41:58',
                'deleted_at' => NULL,
            ),
            46 => 
            array (
                'id' => 83,
                'uuid' => 'f5623e07-5c28-42ce-9ea4-f7521793af7a',
                'category_id' => 83,
                'category_name' => 'العلوم والتكنولوجيا',
                'slug' => 'science-ar',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 19:42:32',
                'updated_at' => '2025-06-26 19:42:32',
                'deleted_at' => NULL,
            ),
            47 => 
            array (
                'id' => 84,
                'uuid' => 'aba18a49-10b6-4ab2-8fa2-748dd9609cbb',
                'category_id' => 84,
                'category_name' => 'الرأي والمقالات',
                'slug' => 'opinion-ar',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 19:43:03',
                'updated_at' => '2025-06-26 19:43:03',
                'deleted_at' => NULL,
            ),
            48 => 
            array (
                'id' => 85,
                'uuid' => 'e7b49476-17b6-4c0f-9ef1-6e97a368a76e',
                'category_id' => 85,
                'category_name' => 'المنوعات والترفيه',
                'slug' => 'lifestyle',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 3,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-26 19:43:28',
                'updated_at' => '2025-06-26 19:43:28',
                'deleted_at' => NULL,
            ),
            49 => 
            array (
                'id' => 86,
                'uuid' => 'da347bfd-d50b-43ac-b24c-5af4a54c7252',
                'category_id' => 86,
                'category_name' => 'Crime',
                'slug' => 'crime-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 1,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-28 23:11:07',
                'updated_at' => '2025-07-26 21:27:52',
                'deleted_at' => NULL,
            ),
            50 => 
            array (
                'id' => 87,
                'uuid' => '812043af-c16d-46ad-9352-8ea084dbc871',
                'category_id' => 87,
                'category_name' => 'Food',
                'slug' => 'food-news',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-28 23:11:44',
                'updated_at' => '2025-07-21 01:30:43',
                'deleted_at' => NULL,
            ),
            51 => 
            array (
                'id' => 88,
                'uuid' => '27406dab-ea96-4d8c-8b8e-e163e181704f',
                'category_id' => 88,
                'category_name' => 'Social Media',
                'slug' => 'social-media',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-28 23:12:23',
                'updated_at' => '2025-06-28 23:12:23',
                'deleted_at' => NULL,
            ),
            52 => 
            array (
                'id' => 89,
                'uuid' => 'ed14b25d-d4c8-48a7-be24-93cb88e845f0',
                'category_id' => 89,
                'category_name' => 'Agriculture',
                'slug' => 'agriculture',
                'menu' => 0,
                'position' => 1,
                'parents_id' => NULL,
                'language_id' => 1,
                'category_imgae' => '',
                'img_status' => 0,
                'category_type' => 1,
                'description' => NULL,
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => NULL,
                'meta_description' => NULL,
                'color_code' => '#000000',
                'created_at' => '2025-06-28 23:12:51',
                'updated_at' => '2025-06-28 23:12:51',
                'deleted_at' => NULL,
            ),
            53 => 
            array (
                'id' => 90,
                'uuid' => 'd99d12b5-5b1e-40e6-a541-483ea43f5569',
                'category_id' => 90,
                'category_name' => 'news',
                'slug' => 'news-topic',
                'menu' => 0,
                'position' => 1,
                'parents_id' => '88',
                'language_id' => 1,
                'category_imgae' => 'category/1753681295809.jpg',
                'img_status' => 0,
                'category_type' => 1,
                'description' => 'news-topic',
                'created_by' => 1,
                'updated_by' => 1,
                'meta_keyword' => 'keyword1,keyword2',
                'meta_description' => 'this is news category',
                'color_code' => '#000000',
                'created_at' => '2025-07-28 17:41:35',
                'updated_at' => '2025-07-28 17:41:35',
                'deleted_at' => NULL,
            ),
        ));
        
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}